### ISSUE TITLE
Javascript error - perform Export as DataPackage for second time

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/comma-chameleon#110]
On OSX when attempting to perform Export as DataPackage for second time, I get...

<img width="433" alt="screenshot 2016-07-26 08 21 29" src="https://cloud.githubusercontent.com/assets/9379524/17119632/6f0b01a8-530a-11e6-859d-d48636a00789.png">

The first export worked successfully.

**Comment by danfowler** [comment]
Having this issue, too.
