### ISSUE TITLE
Insert column left bug

### ISSUE THREAD

**Issue by timpulver** [theodi/comma-chameleon#116]
When right clicking and pressing «insert column left» on a row, the row is inserted two to the left, not one, so there is a jump.

<img width="372" alt="bildschirmfoto 2016-09-09 um 11 29 08" src="https://cloud.githubusercontent.com/assets/1055819/18382306/aba55af2-7680-11e6-9baf-18abd82344b2.png">
<img width="296" alt="bildschirmfoto 2016-09-09 um 11 29 14" src="https://cloud.githubusercontent.com/assets/1055819/18382310/b0649db4-7680-11e6-9d35-3adb469d7050.png">

**Comment by chris48s** [comment]
fixed in #125
