### ISSUE TITLE
Possibility to specify other separators

### ISSUE THREAD

**Issue by albinblaschka** [theodi/comma-chameleon#117]
Hi!
Would it possible to specify different separators for the CSV-file, both with reading and writing, please?
In Europe, specially Central Europe, the separator for CSV-files is often ";" not "," - the latter is our decimal separator and not the point as in English-speaking countries...
In general, being able to specify a custom separator (semi-colon, tab, pipe, ...) would be a big enhancement!
Thanks for considering,
Albin

**Comment by danfowler** [comment]
On "Export to Data Package", the fix for this issue should also include the CSV Dialect in the resource: http://specs.frictionlessdata.io/csv-dialect/

**Comment by chris48s** [comment]
I have been thinking about this issue a little bit..

The jquery-csv functions `toArrays()`, `fromArrays()`, etc can be passed an `options` object. So, for example, to export a csv using semicolon as a separator, the line
https://github.com/theodi/comma-chameleon/blob/master/renderer/file-actions.js#L12
could be edited to pass in an appropriate `options` object. e.g:
`data = $.csv.fromArrays(hot.getData(), { separator: ';', delimiter: '"'});`

However, the less obvious part of this is how to allow the user to specify appropriate values for `separator` and `delimiter` in a non-onerous way. There's a few ways I can see of doing this:

* settings/options: Store an application-level setting for default `separator` and `delimiter` characters. This probably works well for output (assuming the user mostly wants to export using a set format), but it is probably too cumbersome to change an application-level setting each time you want to import a differently formatted file.
* presets: In `file.js`, filters are defined e.g: https://github.com/theodi/comma-chameleon/blob/master/main/file.js#L5 These filters could be expanded to support some other popular conventions e.g: `{ name: 'tab-separated', extensions: ['txt', 'dat'] }` and these filter values could be used to infer appropriate values for `separator` and `delimiter`. This allows the user to pick a format from a list at import/export time, but would be less flexible/difficult to comprehensively support a wide range of obscure formats.
* auto-detect (import-only): You could attempt to auto-detect settings when opening files using a method like this http://stackoverflow.com/a/19070276 but this only works if the input file is properly formatted and perhaps goes against the idea of a feature like 'fix ragged rows'.

Anyone have any other thoughts on this? Should the same solution be used for both save and open actions?

**Comment by pezholio** [comment]
My :+1: would be for presets. I think the application level settings idea is a little too fiddly, and I link the idea of auto-detect, but this is probably a little too error prone. We'd also need to think about how we pass the dialect into CSVlint for validation.

**Comment by chris48s** [comment]
I'm now working on this in PR #120

**Comment by pezholio** [comment]
Fixed by #120
