### ISSUE TITLE
Tests occasionally failing in Travis

### ISSUE THREAD

**Issue by pezholio** [theodi/comma-chameleon#130]
The tests in https://github.com/theodi/comma-chameleon/blob/master/test/renderer/file_actions_spec.js are failing ocassionally in Travis. I thought this was down to a lack of callbacks, but it still seems to be happening.

**Comment by chris48s** [comment]
Having thought about this a bit, I think this is a race condition.

In the test, we call `file_actions.save()` then immediately call `fs.readFile()`, but `save()` is asyncronous so it may or may not have actually finished saving by the time `fs.readFile()` is executed.

What we actually need to do here is (scruffy pseudo-code):

**file.js**
```
fs.writeFile(fileName, data, function (err) {
  if (err) throw err;
  // fire 'someEvent'..
});
```

..and then in the unit test:

**file_actions_spec.js**
```
// ....
file_actions.save(hot, os.tmpdir() + '/mycsv.csv');

on('someEvent', function() {
  fs.readFile(os.tmpdir() + '/mycsv.csv' //bla bla bla...
});
```

That way, `os.tmpdir() + '/mycsv.csv'` is gauranteed to exist before you try to read from it.

**Comment by chris48s** [comment]
Not seen this failure occur since #132 so closing
