### ISSUE TITLE
How to contribute Help text?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/comma-chameleon#149]
The help in Comma Chameleon isn't that helpful. It shows you where the menu functions are and not much more. 

How can I contribute help text to this project?

**Comment by chris48s** [comment]
* Add a HTML page containing some documentation in ` views/views-content/mynewhelpfile.html`
* Add a function to pop up the help page in a new dialog in `main/help.js`
* Create a sub-menu item in the help menu in `main/menu.js` which calls your function

You can use this commit: https://github.com/theodi/comma-chameleon/pull/128/commits/478ddfbaf7d48d7d1bf6a94739e7a2e99dfe3dd1 as a template you can follow.

Thanks

**Comment by Stephen-Gates** [comment]
Thanks @chris48s 
I'll make a start. 🤞

**Comment by Stephen-Gates** [comment]
I'm busy writing but closing this as my question is answered
