### ISSUE TITLE
Count number of downloads

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/comma-chameleon#166]
Count the number of downloads of each comma chameleon distribution so we can report on uptake and if users are staying current with updates

**Comment by Stephen-Gates** [comment]
Oh! There's an API for that: 

- curl -i https://api.github.com/repos/theodi/comma-chameleon/releases/latest
- curl -i https://api.github.com/repos/theodi/comma-chameleon/releases

So for the latest release:

| OS | Downloads |
|---|---|
| Linux 32 | 6 |
| Linux 64 | 52 |
| Windows 32 | 73 |
| Windows 32 | 219 |
| MacOS | 586 |


936 downloads in total

**Comment by quadrophobiac** [comment]
thanks again for this Stephen
