### ISSUE TITLE
Launch blog for comma chameleon

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/comma-chameleon#176]
_From @Floppy on April 25, 2016 8:45_

_Copied from original issue: theodi/shared#924_

**Comment by Stephen-Gates** [comment]
Done?
https://theodi.org/blog/unveiling-comma-chameleon

**Comment by quadrophobiac** [comment]
ha yeah you're in there before me, I've just been pulling some tickets out of a shared repository so they can be filed against their correct toolbox application
