### ISSUE TITLE
Implement Handsontable Jasmine tests

### ISSUE THREAD

**Issue by bcouston** [theodi/comma-chameleon#18]
Jasmine tests currently missing from Handsontable module.

**Comment by bcouston** [comment]
Added instructions in the README (https://github.com/theodi/edward-csvhands/commit/6dd657650606ed24bb9200c87a6411f6b71b9fd2) to run tests. Perhaps would be better to implement in project itself.

**Comment by quadrophobiac** [comment]
IIRC jasmine has been superceded by electron-mocha in the current master so closing this issue
