### ISSUE TITLE
Render CSVlint messages in standard way

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/comma-chameleon#30]
Return the validation JSON in matter that correlates to the CSVLint translations.yaml file that contains ordered messages to go with errors warnings and info_messages.
Something like this but longer 
document.getElementById("message-panel").innerHTML = JSON.stringify(errors)+JSON.stringify(warnings)+JSON.stringify(info_messages);
  });
}

**Comment by danielgavrilov** [comment]
#38 adds validation messages to the pane, but they are not quite descriptive as only their [types](https://github.com/theodi/csvlint.rb/blob/master/README.md#errors) are shown. More descriptive messages would be nicer in the future, but not a priority right now.
