### ISSUE TITLE
Handsontable doesn't auto-adjust on resize

### ISSUE THREAD

**Issue by danielgavrilov** [theodi/comma-chameleon#45]
I've noticed that **sometimes** Handsontable doesn't resize properly:

![](http://g.recordit.co/clU9BE8OWp.gif)

Anyone else noticed this?

**Comment by pezholio** [comment]
I've not, but then I haven't done much resizing. Wonder if this is an elecron thing, or a Handsontable thing? If it's an electron thing, we might be able to redraw the table on a resize event or something
