### ISSUE TITLE
Use CSVlint gem

### ISSUE THREAD

**Issue by pezholio** [theodi/comma-chameleon#58]
Rather than calling an external API.

Could use https://github.com/phusion/traveling-ruby for this

**Comment by pezholio** [comment]
There's also a JS version, which might be easier than packaging Ruby - https://www.npmjs.com/package/csvlint. Not sure if the error structure is the same

**Comment by danielgavrilov** [comment]
The csvlint npm package only reports 2 errors (equivalent to `stray_quote` & `ragged_rows`), so not really useful.

**Comment by pezholio** [comment]
Traveling Ruby is a bit touch and go on Windows, but I did find this https://github.com/jruby/warbler/, which packages up your code as a .jar file. Only problem then is the end user will need Java installed :/
