### ISSUE TITLE
Insert Above/Below misnamed

### ISSUE THREAD

**Issue by scraperdragon** [theodi/comma-chameleon#69]
In spreadsheets, Insert Above when selecting a cell/row will add a new blank row immediately above that row (e.g. if done on row 3, there will be a new blank row 3, the contents of row 3 will be on row 4 etc.) Instead the application adds at the top and bottom.

(It's not clear whether the names or the behaviour should be changed. If the behaviour is changed, the behaviour for left/right should also be changed.)

**Comment by scraperdragon** [comment]
Related: Insert row above is greyed out for row 1; whichever behaviour is correct, there does not seem to be a good reason to do so.

**Comment by chris48s** [comment]
both fixed in #125
