### ISSUE TITLE
Fixed size viewport

### ISSUE THREAD

**Issue by scraperdragon** [theodi/comma-chameleon#70]
![image](https://cloud.githubusercontent.com/assets/1957682/9346983/854aa916-461b-11e5-9085-ff5cfa23f4dd.png)
Resizing the window/Maximising the window leads to unusable screen areas which cannot be clicked on or viewed without using the scrollbar.

**Comment by scraperdragon** [comment]
This may be fixed by entering some data

**Comment by pezholio** [comment]
Yeah, I think we need to force a redraw every time the window is resized. This should be doable.
