### ISSUE TITLE
UI: Export as datapackage

### ISSUE THREAD

**Issue by scraperdragon** [theodi/comma-chameleon#72]
* First field not selected by default
* Tab order wrong (Go/Cancel before Generate Headers
* Keywords can contain spaces (`ko, ko` will lead to two different keywords)
* Possible to not specify headers or not -- should be visibly set to default.

**Comment by morty** [comment]
Also the name field should only allow lower case letters, hyphens and underscores.

It would probably be better to put the title first and then sluggify it into the name field as the user types.
