### ISSUE TITLE
Support "Open With" functionality

### ISSUE THREAD

**Issue by pezholio** [theodi/comma-chameleon#75]
If I try and open a CSV with Comma Chameleon, it starts as normal. I imagine Electron will allow us to do this

**Comment by Floppy** [comment]
Yep, just found this too. Is this on all platforms or just OSX?

**Comment by Xyvir** [comment]
This is happening on Windows 10 Professional as well, presumably all version of Windows. I made Comma Chameleon the default application for opening CSV files, but it always opens a blank "untitled" document. I tested launching the comma-chameleon.exe from CMD using a parameter of a file-name, and that didn't work either, so I presume that is why Open With isn't working.

**Comment by liquidsunshine** [comment]
Just to confirm, this is happening on Windows 7 Enterprise too.  (It's not just a Windows 10 thing.)
