### ISSUE TITLE
Warning returns column number not name (letters)

### ISSUE THREAD

**Issue by BobHarper1** [theodi/comma-chameleon#80]
E.g. I have a warning telling me that data in' column 35' is inconsistent.

But this makes it difficult the probelm, of course, are identified by letters, so in this case AI, but I have to do this manually.

Better to say 'column AI' etc. Also, column could be highlighted, even better.

**Comment by pezholio** [comment]
Sorry for the HUGE delay on this. I'm working on a fix now.
