### ISSUE TITLE
Visual design

### ISSUE THREAD

**Issue by bcouston** [theodi/comma-chameleon#9]
As a CSV editor
I want to implement a visually appealing appearance to the application.
I want it to have a consistent theme.
To appeal to users and make it more user-friendly.

**Comment by Stephen-Gates** [comment]
Was this design documented? If so, can it be shared?

**Comment by quadrophobiac** [comment]
No I can remember that this definitely wasn't documented beyond "that'd be nice to have".  #28 is more explicit about the visual design so closing this issue
