### ISSUE TITLE
Error when resizing window

### ISSUE THREAD

**Issue by Floppy** [theodi/comma-chameleon#95]
Opened a file, dragged out the window to expand it, and BOOM:

<img width="745" alt="screen shot 2016-04-25 at 11 25 25" src="https://cloud.githubusercontent.com/assets/3565/14781117/7af3ce2a-0ad8-11e6-9ad9-9723f540f11b.png">

**Comment by Floppy** [comment]
Pressing OK resulted in the same error again, then once that was acknowledged, the window was resized but the content wasn't.

**Comment by jennybc** [comment]
I am getting this error on every resize.

**Comment by awhitehouse104** [comment]
Also get the error on every resize, windows 8.1

**Comment by zkamvar** [comment]
I get this error with existing csv files using version 0.4.8
